#!/bin/bash
# LocalPro AI Lead Engine - Development Setup & Testing Guide

set -e

echo "🚀 LocalPro AI Lead Engine - Development Setup"
echo "================================================"
echo ""

# Step 1: Check if Chrome is available
echo "✓ Step 1: Verifying environment"
if command -v google-chrome &> /dev/null || command -v chromium &> /dev/null; then
    echo "  ✓ Chrome/Chromium found"
else
    echo "  ⚠ Chrome not found. You'll need to load the extension manually."
fi

# Step 2: Build the extension
echo ""
echo "✓ Step 2: Building extension..."
npm run build
echo "  ✓ Build complete"

# Step 3: Display next steps
echo ""
echo "✓ Step 3: Ready to test!"
echo ""
echo "📋 Next Steps:"
echo ""
echo "  1. LOAD EXTENSION IN CHROME:"
echo "     • Go to: chrome://extensions/"
echo "     • Enable: Developer mode (toggle in top-right)"
echo "     • Click: 'Load unpacked'"
echo "     • Select: $(pwd)/dist"
echo ""
echo "  2. TEST LEAD CAPTURE:"
echo "     • Navigate to: https://www.facebook.com/marketplace"
echo "     • Look for: 'Capture Lead' buttons on Marketplace listings"
echo "     • Or click extension icon → 'Scan Current Tab'"
echo ""
echo "  3. VERIFY FUNCTIONALITY:"
echo "     ✓ Lead classification (service type, urgency)"
echo "     ✓ Budget estimation"
echo "     ✓ Lead history tracking"
echo "     ✓ Stats dashboard"
echo ""
echo "  4. CHECK CONSOLE LOGS:"
echo "     • Press F12 to open DevTools"
echo "     • Check Console for [LocalPro] messages"
echo "     • Check Extension background worker logs:"
echo "       chrome://extensions → LocalPro Lead Engine → Service Worker"
echo ""
echo "🔧 TESTING CHECKLIST:"
echo ""
echo "  Content Script Tests:"
echo "    [ ] Lead extraction from FB Marketplace"
echo "    [ ] Lead extraction from FB Groups"
echo "    [ ] Lead extraction from Google Business"
echo "    [ ] Lead extraction from Messenger"
echo "    [ ] UI button injection on page load"
echo "    [ ] Button injection on dynamic content"
echo ""
echo "  Classification Tests:"
echo "    [ ] Service type detection (test each: plumbing, cleaning, etc.)"
echo "    [ ] Urgency extraction (test: same-day, urgent, high, medium, low)"
echo "    [ ] Budget estimation"
echo "    [ ] Confidence scoring"
echo ""
echo "  UI Tests:"
echo "    [ ] Popup loads correctly"
echo "    [ ] Login/logout works"
echo "    [ ] Lead stats display correctly"
echo "    [ ] Lead history shows captured leads"
echo "    [ ] Platform badges update"
echo ""
echo "  Integration Tests:"
echo "    [ ] Lead capture end-to-end"
echo "    [ ] Lead history persistence"
echo "    [ ] Badge count updates"
echo "    [ ] Error handling (invalid lead, network error)"
echo ""
echo "🐛 DEBUGGING:"
echo ""
echo "  View Messages:"
echo "    chrome://extensions → LocalPro → Details → Background Service Worker"
echo ""
echo "  Test Content Script:"
echo "    • F12 on any supported site"
echo "    • Console should show: [LocalPro] Content script active on [platform]"
echo ""
echo "  Test Message Passing:"
echo "    • Open DevTools Console on popup"
echo "    • Execute: chrome.runtime.sendMessage({type: 'GET_LEAD_STATS'}, r => console.log(r))"
echo ""
echo "📝 SAMPLE TEST LEADS:"
echo ""
echo "  Plumbing:"
echo "    'URGENT! Leaky toilet needs immediate fix. ASAP. Will pay ₱300-500'"
echo "    Expected: Service=plumbing, Urgency=same-day, Budget=300-500"
echo ""
echo "  Cleaning:"
echo "    'Looking for someone to clean my house this weekend. Budget around ₱1000'"
echo "    Expected: Service=cleaning, Urgency=medium, Budget=800-1200"
echo ""
echo "  Electrical:"
echo "    'Can anyone fix my broken outlet? No rush, whenever available.'"
echo "    Expected: Service=electrical, Urgency=low, Budget=100-150"
echo ""
echo "✨ All done! Happy testing!"
